#!/usr/bin/bash

# This script is meant to be used with i3blocks.
# It parses the output of "pactl" command to determine
# whether default audio source is muted.

MIC=`pactl get-source-mute @DEFAULT_SOURCE@ | cut -d ' ' -f2`

if [ $MIC = "yes" ];
then
    echo "" # full_text
    echo "" # short_text
else
    echo "" # full_text
    echo "" # short_text
fi
