#!/usr/bin/bash

# This script is meant to be used with i3blocks.
# It parses the output of "pactl" command to determine
# whether default audio sink is muted.

MUTE=`pactl get-sink-mute @DEFAULT_SINK@ | cut -d ' ' -f2`

if [ $MUTE = "yes" ];
then
    echo "" # full_text
    echo "" # short_text
else
    echo "" # full_text
    echo "" # short_text
fi
