#!/usr/bin/bash

# Handle script arguments.
STEP="-5%"
TOGGLE_MUTE=0
if [ $# -gt 0 ];
then
    if [ $1 = "toggle" ];
    then
        TOGGLE_MUTE=1
    else
        STEP=$1
    fi
fi

# Toggle mute or change volume.
if [ $TOGGLE_MUTE -eq 0 ];
then
    pactl set-sink-volume @DEFAULT_SINK@ $STEP
else
    pactl set-sink-mute @DEFAULT_SINK@ toggle
fi

# Query volume and mute status.
VOLUME=`pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{print $5}' | sed 's/[^0-9]*//g'`
MUTE=`pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}'`

# Arbitrary but unique message tag.
MSG_TAG="volumeNotif"

# Send notification to dunst.
if  [ $MUTE = "yes" ];
then
    dunstify -i audio-volume-muted -h string:x-dunst-stack-tag:$MSG_TAG "Volume muted"
else
    dunstify -i audio-volume-high -h string:x-dunst-stack-tag:$MSG_TAG -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
fi
